name: drupal-8-lando
recipe: drupal8
config:
  php: 7.1
  via: apache:2.4
  webroot: docroot
  xdebug: true
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        # Support debugging Drush with XDEBUG.
        PHP_IDE_CONFIG: "serverName=http://drupal-8-lando.lndo.site"
  database:
    type: mysql
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: drupal
  mariadatabase:
    type: mariadb
    portforward: true
    creds:
      user: drupal
      password: drupal
      database: drupal
